# Generated by Django 4.1.1 on 2022-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
