# Generated by Django 4.1.1 on 2022-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reports_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
