# Generated by Django 4.1.1 on 2022-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reports_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
